# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('style', models.ImageField(blank=True, upload_to='')),
                ('material_sample', models.ImageField(blank=True, upload_to='')),
                ('amount_charged', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
