# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='material_sample',
            field=models.ImageField(blank=True, upload_to='sample/'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='style',
            field=models.ImageField(blank=True, upload_to='style/'),
        ),
    ]
