# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blouse',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gown',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='measurement',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shirt',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skirt',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trouser',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
