# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_auto_20171003_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('length', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shoulder', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('half_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bust', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('waist', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('under_burst_waist', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hip', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sleeve_length', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('round_sleeve_short', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('round_sleeve_long', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('style', models.ImageField(blank=True, upload_to='style/')),
                ('material_sample', models.ImageField(blank=True, upload_to='sample/')),
            ],
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='material_sample',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='style',
        ),
        migrations.AddField(
            model_name='shirt',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurements.Measurement'),
        ),
    ]
