# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_auto_20171003_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
