# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0004_shirt_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='name',
            field=models.CharField(default=True, max_length=250),
        ),
    ]
