# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0005_auto_20171003_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
