# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0006_auto_20171003_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shirt',
            old_name='under_burst_waist',
            new_name='underbust_waist',
        ),
    ]
